### ISSUE TITLE
Todo: Clarify location & filter parameters

### ISSUE THREAD

**Issue by Diddlik** [mgp25/Instagram-API#1091]
### Before submitting an issue make sure you have:
- [x] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [x] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [x] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [x] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

Hallo, I try to post an image with location parameter, but I did not found a proper way hot to set the parameters for it. 
May can you help me?

Sincerely,
Pavel

**Comment by SteveJobzniak** [comment]
Hi Diddlik. I think location is just a number like "1123939912" and corresponds to these URLs:

https://www.instagram.com/explore/locations/567005557/antarctica/

So "567005557" is antarctica.

You can search for locations by name via some functions in this library. Look closely.

**Comment by SteveJobzniak** [comment]
Actually I'll reopen this and make it an issue. The code comments for the `$location` parameters really should be clarified.

**Comment by SteveJobzniak** [comment]
Also: https://github.com/mgp25/Instagram-API/issues/1096

The code comments for the `$location` and `$filter` parameters need fixing.

**Comment by mgp25** [comment]
`$location` is a Location Object (https://github.com/mgp25/Instagram-API/blob/master/src/http/Response/Objects/Location.php). 

You can get set it manually or get it using one of these functions: `searchFBLocation` and `searchFBLocationByPoint`

About `$filter` its a value refering the filter used while uploading the media, but since photo modification occurs in the device, here it wont have any effect, so better dont use it.

Regards
